# Generated by Django 5.2.9 on 2026-01-22 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_city_city_name_en_city_city_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='property_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.property'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.property'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.room'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.room'),
        ),
    ]
