# Generated by Django 5.2.9 on 2026-01-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0003_propertyimage_property_en_propertyimage_property_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='room_ru',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room_en',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
